filter:
  excluded_paths:
    - 'current/assets'
    - 'current/config'
    - 'current/data'
    - 'current/frontend'
    - 'current/grunt'
    - 'current/public'
    - 'current/tests'
    - 'current/src/Pyz/Zed/DataImport/Business/DataImportBusinessFactory.php'

  dependency_paths:
    - 'current/src/Generated/'
    - 'current/src/Orm/'
    - 'current/vendor/'

build:
  root_path: './current'

  environment:
      php: '7.1'
      node: '8.10.0'

      variables:
        APPLICATION_ENV: development
        APPLICATION_STORE: DE

  dependencies:
      before:
          - 'rm -rf ./node_modules'
          - 'npm cache -f clear'
          - 'composer remove --dev spryker/git-hook'

  tests:
    before:
      - 'vendor/bin/console transfer:generate'
    override:
      - php-scrutinizer-run --enable-security-analysis

checks:
  php:
    no_exit: false

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true