version: '3.2'
services:
  data:
    ports:
      - "2222:22"
  db:
    ports:
      - 5432:5432
  redis:
    ports:
      - 6379:6379
  elasticsearch:
    ports:
      - 9200:9200
  rabbitmq:
    ports:
      - 15672:15672
  jenkins:
    ports:
      - 8080:8080
  loadbalancer:
    ports:
     - "80:80"
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - 1080:1080
  redisui:
    image: tenstartups/redis-commander
    container_name: redisui
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"